# Generated by Django 3.2.5 on 2021-07-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_habittracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goaltype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
